### ISSUE TITLE
Can't click Save

### ISSUE THREAD

**Issue by ThatSameChap** [erkle64/Duplicationer#3]
I can't click save when trying to save the blueprint. Whenever I press it, it does nothing. I've selected images and changed the name, I've tried not doing both of these. I'm using the mod Via the Foundry Mod Manager (0.5.7)

![image](https://github.com/erkle64/Duplicationer/assets/74638500/34fb8945-20b3-4aee-8e30-298aae22f821)

Edit: Image added for context of which particular save button

**Comment by erkle64** [comment]
Thanks for reporting it.  The latest hotfix changed a function name.  Fixed in [v0.4.23](https://github.com/erkle64/Duplicationer/releases/tag/v0.4.23).

**Comment by ThatSameChap** [comment]
Thank you!
